version = 0.1
[default.deploy.parameters]
stack_name = "unicorn-store"
resolve_s3 = true
s3_prefix = "unicorn-store"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
